// GENERATED by 'npm run build:fn' from server/agent/ — do not edit.

// server/agent/handler.ts
import OpenAI from "openai";
import { createClient } from "@supabase/supabase-js";

// src/agent/types.ts
function emptyContext() {
  return { shownProductIds: [], selectedProductIds: [], preferences: {} };
}

// server/agent/env.ts
function readAgentEnv(raw) {
  const pick = (...keys) => {
    for (const k of keys) {
      const v2 = raw[k];
      if (v2 && v2.trim()) return v2.trim();
    }
    return "";
  };
  return {
    openaiApiKey: pick("OPENAI_API_KEY"),
    model: pick("AI_MODEL") || "gpt-4o-mini",
    supabaseUrl: pick(
      "SUPABASE_URL",
      "VITE_SUPABASE_URL",
      "NEXT_PUBLIC_SUPABASE_URL"
    ),
    supabaseAnonKey: pick(
      "SUPABASE_ANON_KEY",
      "VITE_SUPABASE_ANON_KEY",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY"
    )
  };
}

// server/agent/catalog.ts
function totalStock(p) {
  return p.variants.reduce(
    (sum, v2) => sum + Object.values(v2.stockByLocation).reduce((a, b) => a + b, 0),
    0
  );
}
var STOP = /* @__PURE__ */ new Set([
  "the",
  "and",
  "for",
  "with",
  "something",
  "need",
  "want",
  "show",
  "have",
  "looking",
  "under",
  "below",
  "over",
  "about",
  "some",
  "that",
  "this"
]);
function rankProducts(products, filters, limit = 8) {
  const terms = `${filters.query ?? ""} ${filters.occasion ?? ""} ${filters.style ?? ""}`.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter((t) => t.length > 2 && !STOP.has(t));
  const scored = products.map((p) => {
    const hay = [
      p.name,
      p.brand,
      p.style,
      p.category,
      p.gender,
      p.material,
      p.description,
      p.variants.map((v2) => v2.color).join(" ")
    ].filter(Boolean).join(" ").toLowerCase();
    let score = 0;
    for (const t of terms) if (hay.includes(t)) score += 2;
    if (terms.length === 0) score += 1;
    const hard = (field, hs) => field ? hs.includes(field.toLowerCase()) ? 1 : -3 : 0;
    score += hard(filters.category, p.category?.toLowerCase() ?? "");
    score += hard(filters.style, p.style?.toLowerCase() ?? "");
    score += hard(filters.gender, p.gender?.toLowerCase() ?? "");
    if (filters.color) {
      const colors = p.variants.map((v2) => v2.color?.toLowerCase() ?? "").join(" ");
      score += colors.includes(filters.color.toLowerCase()) ? 1 : -2;
    }
    if (filters.size) {
      const sizes = p.variants.map((v2) => v2.size?.toLowerCase() ?? "").join(" ");
      score += sizes.includes(filters.size.toLowerCase()) ? 1 : -2;
    }
    if (filters.minPriceCents != null && p.priceCents < filters.minPriceCents)
      score -= 3;
    if (filters.maxPriceCents != null && p.priceCents > filters.maxPriceCents)
      score -= 5;
    return { p, score };
  }).filter((x) => x.score > 0 && totalStock(x.p) > 0).sort((a, b) => b.score - a.score || a.p.priceCents - b.p.priceCents);
  return scored.slice(0, limit).map((x) => x.p);
}
var DbCatalog = class {
  db;
  storeId;
  currency;
  locations;
  constructor(db, storeId, currency, locations) {
    this.db = db;
    this.storeId = storeId;
    this.currency = currency;
    this.locations = locations;
  }
  get multiLocation() {
    return this.locations.length > 1;
  }
  map(rows) {
    return rows.map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      brand: p.brand,
      style: p.style,
      gender: p.gender,
      material: p.material,
      care: p.care,
      category: p.category,
      priceCents: p.price_cents,
      currency: p.currency,
      imageUrl: p.image_url,
      variants: (p.product_variants ?? []).map((v2) => ({
        id: v2.id,
        size: v2.size,
        color: v2.color,
        priceCents: v2.price_cents,
        stockByLocation: Object.fromEntries(
          (v2.inventory ?? []).map((i) => [i.location_id, i.quantity])
        )
      }))
    }));
  }
  async all() {
    const { data, error } = await this.db.from("products").select("*, product_variants(*, inventory(*))").eq("store_id", this.storeId).eq("status", "active");
    if (error) throw new Error(error.message);
    return this.map(data ?? []);
  }
  async byIds(ids) {
    if (ids.length === 0) return [];
    const { data, error } = await this.db.from("products").select("*, product_variants(*, inventory(*))").eq("store_id", this.storeId).in("id", ids);
    if (error) throw new Error(error.message);
    return this.map(data ?? []);
  }
};
var DemoCatalog = class {
  currency = "USD";
  locations = [
    { id: "orchard", name: "Orchard" },
    { id: "vivocity", name: "VivoCity" },
    { id: "jurong", name: "Jurong East" }
  ];
  get multiLocation() {
    return true;
  }
  products = DEMO_PRODUCTS;
  async all() {
    return this.products;
  }
  async byIds(ids) {
    return this.products.filter((p) => ids.includes(p.id));
  }
};
function v(id, size, color, stock) {
  return { id, size, color, priceCents: null, stockByLocation: stock };
}
var DEMO_PRODUCTS = [
  {
    id: "demo-linen-blazer",
    name: "Linen Blazer",
    description: "Relaxed-fit oatmeal linen blazer, half-lined with a natural shoulder. Reads smart without feeling stiff.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Mens",
    material: "100% linen",
    care: "Dry clean",
    category: "Blazers",
    priceCents: 8900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dlb-s-oat", "S", "Oatmeal", { orchard: 2, vivocity: 1, jurong: 0 }),
      v("dlb-m-oat", "M", "Oatmeal", { orchard: 4, vivocity: 2, jurong: 0 }),
      v("dlb-l-oat", "L", "Oatmeal", { orchard: 3, vivocity: 0, jurong: 1 })
    ]
  },
  {
    id: "demo-tailored-jacket",
    name: "Tailored Jacket",
    description: "Structured navy jacket with a sharp shoulder and a clean lapel. The formal end of the rail.",
    brand: "Urban Thread",
    style: "Formal",
    gender: "Mens",
    material: "Wool blend",
    care: "Dry clean",
    category: "Blazers",
    priceCents: 12900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dtj-m-nvy", "M", "Navy", { orchard: 2, vivocity: 1, jurong: 0 }),
      v("dtj-l-nvy", "L", "Navy", { orchard: 1, vivocity: 1, jurong: 0 })
    ]
  },
  {
    id: "demo-overshirt",
    name: "Relaxed Overshirt",
    description: "Lightweight taupe overshirt with chest pockets. Layer it open or button it up.",
    brand: "Urban Thread",
    style: "Casual",
    gender: "Unisex",
    material: "Cotton twill",
    care: "Machine wash cold",
    category: "Shirts",
    priceCents: 7200,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dos-s-tpe", "S", "Taupe", { orchard: 3, vivocity: 2, jurong: 4 }),
      v("dos-m-tpe", "M", "Taupe", { orchard: 6, vivocity: 3, jurong: 5 }),
      v("dos-l-tpe", "L", "Taupe", { orchard: 2, vivocity: 1, jurong: 3 })
    ]
  },
  {
    id: "demo-oxford",
    name: "Oxford Shirt",
    description: "Classic cotton oxford. Works under a blazer for dinner or on its own.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Unisex",
    material: "100% cotton",
    care: "Machine wash cold",
    category: "Shirts",
    priceCents: 4900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dox-s-wht", "S", "White", { orchard: 8, vivocity: 6, jurong: 7 }),
      v("dox-m-wht", "M", "White", { orchard: 12, vivocity: 8, jurong: 10 }),
      v("dox-l-wht", "L", "White", { orchard: 5, vivocity: 4, jurong: 6 }),
      v("dox-m-blu", "M", "Blue", { orchard: 4, vivocity: 3, jurong: 2 })
    ]
  },
  {
    id: "demo-trousers",
    name: "Wool Trousers",
    description: "Charcoal tapered wool trousers with a clean drape. Smart casual to formal.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Mens",
    material: "Wool blend",
    care: "Dry clean",
    category: "Trousers",
    priceCents: 9800,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dwt-30-chr", "30", "Charcoal", { orchard: 3, vivocity: 2, jurong: 1 }),
      v("dwt-32-chr", "32", "Charcoal", { orchard: 5, vivocity: 4, jurong: 2 }),
      v("dwt-34-chr", "34", "Charcoal", { orchard: 4, vivocity: 3, jurong: 2 })
    ]
  }
];

// server/agent/tools.ts
var DELIVERY_FEE_CENTS = 500;
function fmtMoney(cents, currency) {
  const amount = cents / 100;
  const s = amount % 1 === 0 ? amount.toFixed(0) : amount.toFixed(2);
  return currency === "USD" ? `$${s}` : `${s} ${currency}`;
}
function variantLabel(v2) {
  return [v2.size, v2.color].filter(Boolean).join(" / ") || "One size";
}
function variantStock(v2) {
  return Object.values(v2.stockByLocation).reduce((a, b) => a + b, 0);
}
var TOOL_SCHEMAS = [
  {
    type: "function",
    function: {
      name: "search_products",
      description: "Search this merchant's catalog. Returns a short list of in-stock candidates. Use for any discovery request.",
      parameters: {
        type: "object",
        properties: {
          query: { type: "string", description: "free-text description of what the shopper wants" },
          category: { type: "string" },
          color: { type: "string" },
          size: { type: "string" },
          style: { type: "string", description: 'e.g. "smart casual", "formal"' },
          occasion: { type: "string", description: 'e.g. "dinner", "wedding"' },
          gender: { type: "string" },
          min_price: { type: "number", description: "in dollars" },
          max_price: { type: "number", description: "in dollars" }
        }
      }
    }
  },
  {
    type: "function",
    function: {
      name: "check_inventory",
      description: "Real stock for a product, optionally narrowed to a size and/or colour. Returns per-location counts for multi-location merchants.",
      parameters: {
        type: "object",
        properties: {
          product_id: { type: "string" },
          size: { type: "string" },
          color: { type: "string" }
        },
        required: ["product_id"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "compare_products",
      description: 'Authoritative facts (description, brand, style, material, care, price, stock) for one or more products already shown. Use for "tell me more about X" and "what is the difference between X and Y". You write the prose; the UI shows a table when there are 2+.',
      parameters: {
        type: "object",
        properties: {
          product_ids: { type: "array", items: { type: "string" }, minItems: 1 }
        },
        required: ["product_ids"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "create_order_preview",
      description: "Deterministic purchase preview. The backend calculates all money. Call once the shopper has chosen product(s), size and colour.",
      parameters: {
        type: "object",
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                product_id: { type: "string" },
                size: { type: "string" },
                color: { type: "string" },
                quantity: { type: "integer", minimum: 1 }
              },
              required: ["product_id"]
            }
          },
          fulfillment: { type: "string", enum: ["delivery", "pickup"] },
          location: { type: "string", description: "pickup location name" }
        },
        required: ["items"]
      }
    }
  }
];
var str = (v2) => typeof v2 === "string" && v2.trim() ? v2.trim() : void 0;
var num = (v2) => typeof v2 === "number" && isFinite(v2) ? v2 : void 0;
function compactProduct(p, currency) {
  const colors = [...new Set(p.variants.map((v2) => v2.color).filter(Boolean))];
  const sizes = [...new Set(p.variants.map((v2) => v2.size).filter(Boolean))];
  return {
    id: p.id,
    name: p.name,
    brand: p.brand ?? void 0,
    category: p.category ?? void 0,
    style: p.style ?? void 0,
    price: fmtMoney(p.priceCents, currency),
    colors: colors.length ? colors : void 0,
    sizes: sizes.length ? sizes : void 0,
    in_stock: totalStock(p) > 0
  };
}
async function executeTool(name, rawArgs, ctx) {
  switch (name) {
    case "search_products": {
      const all = await ctx.catalog.all();
      const ranked = rankProducts(
        all,
        {
          query: str(rawArgs.query),
          category: str(rawArgs.category),
          color: str(rawArgs.color),
          size: str(rawArgs.size),
          style: str(rawArgs.style),
          occasion: str(rawArgs.occasion),
          gender: str(rawArgs.gender),
          minPriceCents: num(rawArgs.min_price) != null ? Math.round(num(rawArgs.min_price) * 100) : void 0,
          maxPriceCents: num(rawArgs.max_price) != null ? Math.round(num(rawArgs.max_price) * 100) : void 0
        },
        8
      );
      ctx.lastSearch = ranked;
      return {
        count: ranked.length,
        recommend_at_most: ctx.recommendationLimit,
        products: ranked.map((p) => compactProduct(p, ctx.currency))
      };
    }
    case "check_inventory": {
      const id = str(rawArgs.product_id);
      if (!id) return { error: "product_id required" };
      const [product] = await ctx.catalog.byIds([id]);
      if (!product) return { error: "product not found" };
      const size = str(rawArgs.size)?.toLowerCase();
      const color = str(rawArgs.color)?.toLowerCase();
      const variants = product.variants.filter(
        (v2) => (!size || v2.size?.toLowerCase() === size) && (!color || v2.color?.toLowerCase() === color)
      );
      const byLoc = ctx.catalog.locations.map((loc) => ({
        location: loc.name,
        quantity: variants.reduce(
          (s, v2) => s + (v2.stockByLocation[loc.id] ?? 0),
          0
        )
      })).filter((l) => l.quantity > 0);
      const total = byLoc.reduce((s, l) => s + l.quantity, 0);
      return {
        product: product.name,
        matched_variants: variants.map((v2) => variantLabel(v2)),
        total,
        in_stock: total > 0,
        ...ctx.catalog.multiLocation ? { by_location: byLoc } : {}
      };
    }
    case "compare_products": {
      const ids = Array.isArray(rawArgs.product_ids) ? rawArgs.product_ids.filter((x) => typeof x === "string") : [];
      const products = await ctx.catalog.byIds(ids);
      ctx.lastCompare = products;
      return {
        products: products.map((p) => ({
          id: p.id,
          name: p.name,
          description: p.description ?? void 0,
          price: fmtMoney(p.priceCents, ctx.currency),
          brand: p.brand ?? void 0,
          style: p.style ?? void 0,
          material: p.material ?? void 0,
          care: p.care ?? void 0,
          category: p.category ?? void 0,
          gender: p.gender ?? void 0,
          sizes: [...new Set(p.variants.map((v2) => v2.size).filter(Boolean))],
          colors: [...new Set(p.variants.map((v2) => v2.color).filter(Boolean))],
          in_stock: totalStock(p) > 0
        }))
      };
    }
    case "create_order_preview": {
      const items = Array.isArray(rawArgs.items) ? rawArgs.items : [];
      const fulfillment = rawArgs.fulfillment === "pickup" ? "pickup" : "delivery";
      const location = str(rawArgs.location) ?? null;
      const ids = items.map((it) => str(it.product_id)).filter((x) => !!x);
      const products = await ctx.catalog.byIds(ids);
      const byId = new Map(products.map((p) => [p.id, p]));
      const lines = [];
      let allInStock = true;
      for (const it of items) {
        const p = byId.get(str(it.product_id) ?? "");
        if (!p) {
          allInStock = false;
          continue;
        }
        const size = str(it.size)?.toLowerCase();
        const color = str(it.color)?.toLowerCase();
        const variant = p.variants.find(
          (v2) => (!size || v2.size?.toLowerCase() === size) && (!color || v2.color?.toLowerCase() === color)
        ) ?? p.variants[0];
        const qty = Math.max(1, Math.round(num(it.quantity) ?? 1));
        const unit = variant?.priceCents ?? p.priceCents;
        if (!variant || variantStock(variant) < qty) allInStock = false;
        lines.push({
          name: p.name,
          variant: variant ? variantLabel(variant) : null,
          quantity: qty,
          unitPriceCents: unit,
          lineTotalCents: unit * qty
        });
      }
      const subtotal = lines.reduce((s, l) => s + l.lineTotalCents, 0);
      const delivery = fulfillment === "delivery" ? DELIVERY_FEE_CENTS : 0;
      const preview = {
        lines,
        subtotalCents: subtotal,
        deliveryCents: delivery,
        totalCents: subtotal + delivery,
        currency: ctx.currency,
        fulfillment,
        location,
        allInStock
      };
      ctx.lastOrderPreview = preview;
      ctx.lastOrderProductIds = [...new Set(ids)];
      return {
        lines: lines.map((l) => ({
          item: `${l.name}${l.variant ? ` (${l.variant})` : ""} x${l.quantity}`,
          line_total: fmtMoney(l.lineTotalCents, ctx.currency)
        })),
        subtotal: fmtMoney(subtotal, ctx.currency),
        delivery: fmtMoney(delivery, ctx.currency),
        total: fmtMoney(subtotal + delivery, ctx.currency),
        all_in_stock: allInStock,
        note: "Show this preview to the shopper. They must press Confirm & Pay themselves."
      };
    }
    default:
      return { error: `unknown tool: ${name}` };
  }
}

// server/agent/prompt.ts
function buildSystemPrompt(cfg) {
  const where = cfg.branchName ? `${cfg.storeName} \u2014 ${cfg.branchName}` : cfg.storeName;
  const lines = [
    `You are StyleSelf's Fashion Commerce Agent for ${where}, a fashion store.`,
    `Help the shopper discover, compare, and buy from this store's real catalog.`,
    `Brand tone: ${cfg.tone}. Prices are in ${cfg.currency}.`,
    cfg.multiLocation ? `This is a multi-location store: ${cfg.locationNames.join(", ")}. Mention where items are in stock.` : cfg.locationNames[0] ? `Single location: ${cfg.locationNames[0]}.` : ``,
    cfg.rules ? `Merchant rules: ${cfg.rules}` : ``,
    ``,
    `How to work:`,
    `- Use tools for every catalog, price, size, stock, and total. Never invent products, prices, sizes, colours, or availability.`,
    `- Discovery -> search_products. "What's the difference / which is better" -> compare_products with the relevant ids. "Is it in stock / in size M" -> check_inventory. Ready to buy -> create_order_preview.`,
    `- The shown-products list tells you what "the first one" / "the cheaper one" refers to \u2014 use those ids directly, no extra search.`,
    `- Recommend at most ${cfg.recommendationLimit} products; lead with your single best pick and say why in one sentence.`,
    `- Ask at most one clarifying question, and only when you genuinely cannot act yet.`,
    `- Keep replies to 2\u20134 short sentences. Plain sentences only \u2014 no markdown, bullet points, dashes, or HTML.`,
    `- Before an order preview, make sure size and colour are chosen. create_order_preview does the maths.`,
    `- After create_order_preview, say one short sentence like "Here's your order \u2014 press Confirm & Pay when ready." Do NOT re-list the line items or totals; the card shows them.`,
    `- Never say an order is placed or paid. The shopper presses "Confirm & Pay" in the UI.`
  ];
  return lines.filter((l) => l !== ``).join("\n");
}
function contextBlock(context, shown, currency) {
  if (shown.length === 0) return null;
  const list = shown.map((p2, i) => `${i + 1}. ${p2.name} \u2014 ${fmtMoney(p2.priceCents, currency)} [id: ${p2.id}]`).join("\n");
  const parts = [`Products currently shown to the shopper:
${list}`];
  if (context.selectedProductIds.length) {
    parts.push(`Selected for purchase: ${context.selectedProductIds.join(", ")}`);
  }
  const p = context.preferences;
  const prefBits = [
    p.budgetCents != null ? `budget ~${fmtMoney(p.budgetCents, currency)}` : null,
    p.sizes?.length ? `sizes ${p.sizes.join("/")}` : null,
    p.colors?.length ? `colours ${p.colors.join("/")}` : null,
    p.occasions?.length ? `occasion ${p.occasions.join("/")}` : null
  ].filter(Boolean);
  if (prefBits.length) parts.push(`Known preferences: ${prefBits.join(", ")}`);
  return parts.join("\n");
}

// server/agent/runtime.ts
var MAX_TOOL_ROUNDS = 3;
var MAX_HISTORY = 8;
function cardFor(p, currency) {
  return {
    id: p.id,
    name: p.name,
    brand: p.brand,
    category: p.category,
    priceCents: p.priceCents,
    currency,
    imageUrl: p.imageUrl,
    inStock: totalStock(p) > 0
  };
}
async function runTurn(openai, model, input) {
  const { catalog, config } = input;
  const context = {
    shownProductIds: [...input.context.shownProductIds],
    selectedProductIds: [...input.context.selectedProductIds],
    preferences: { ...input.context.preferences }
  };
  const shown = context.shownProductIds.length > 0 ? await catalog.byIds(context.shownProductIds) : [];
  const shownOrdered = context.shownProductIds.map((id) => shown.find((p) => p.id === id)).filter((p) => !!p);
  const ctxBlock = contextBlock(context, shownOrdered, config.currency);
  const messages = [
    { role: "system", content: buildSystemPrompt(config) },
    ...ctxBlock ? [{ role: "system", content: ctxBlock }] : [],
    ...input.messages.slice(-MAX_HISTORY).map(
      (m) => ({ role: m.role, content: m.content })
    )
  ];
  const toolCtx = {
    catalog,
    currency: config.currency,
    recommendationLimit: config.recommendationLimit
  };
  let finalText = "";
  for (let round = 0; round < MAX_TOOL_ROUNDS; round++) {
    const completion = await openai.chat.completions.create({
      model,
      messages,
      tools: TOOL_SCHEMAS,
      tool_choice: "auto",
      temperature: 0.3,
      max_tokens: 450
    });
    const choice = completion.choices[0]?.message;
    if (!choice) break;
    if (choice.tool_calls && choice.tool_calls.length > 0) {
      messages.push({
        role: "assistant",
        content: choice.content ?? "",
        tool_calls: choice.tool_calls
      });
      for (const call of choice.tool_calls) {
        if (call.type !== "function") continue;
        let args = {};
        try {
          args = JSON.parse(call.function.arguments || "{}");
        } catch {
          args = {};
        }
        let result;
        try {
          result = await executeTool(call.function.name, args, toolCtx);
        } catch (err) {
          result = { error: err instanceof Error ? err.message : "tool failed" };
        }
        messages.push({
          role: "tool",
          tool_call_id: call.id,
          content: JSON.stringify(result)
        });
      }
      continue;
    }
    finalText = (choice.content ?? "").trim();
    break;
  }
  if (!finalText) {
    finalText = "I'm having trouble putting that together right now \u2014 could you rephrase?";
  }
  let products;
  let comparison;
  let orderPreview = toolCtx.lastOrderPreview;
  let action = { type: "none" };
  if (toolCtx.lastSearch && toolCtx.lastSearch.length > 0) {
    const list = toolCtx.lastSearch.slice(0, config.recommendationLimit);
    const lower = finalText.toLowerCase();
    let recId;
    let bestIdx = Infinity;
    for (const p of list) {
      const idx = lower.indexOf(p.name.toLowerCase());
      if (idx !== -1 && idx < bestIdx) {
        bestIdx = idx;
        recId = p.id;
      }
    }
    const ordered = recId ? [
      ...list.filter((p) => p.id === recId),
      ...list.filter((p) => p.id !== recId)
    ] : list;
    products = ordered.map((p) => ({
      ...cardFor(p, config.currency),
      recommended: p.id === recId
    }));
    context.shownProductIds = ordered.map((p) => p.id);
    action = { type: "show_products" };
  }
  if (toolCtx.lastCompare && toolCtx.lastCompare.length >= 2) {
    const ps = toolCtx.lastCompare;
    const row = (label, get) => ({
      label,
      values: ps.map(get)
    });
    comparison = {
      products: ps.map((p) => ({ id: p.id, name: p.name })),
      rows: [
        row("Price", (p) => fmtMoney(p.priceCents, config.currency)),
        row("Style", (p) => p.style ?? "\u2014"),
        row("Material", (p) => p.material ?? "\u2014"),
        row("Category", (p) => p.category ?? "\u2014"),
        row("For", (p) => p.gender ?? "\u2014"),
        row("In stock", (p) => totalStock(p) > 0 ? "Yes" : "No")
      ]
    };
    action = { type: "show_comparison" };
  }
  if (orderPreview) {
    action = { type: "show_order_preview" };
    if (toolCtx.lastOrderProductIds?.length) {
      context.selectedProductIds = toolCtx.lastOrderProductIds;
    }
  }
  return {
    message: finalText,
    products,
    comparison,
    orderPreview,
    action,
    context
  };
}

// server/agent/handler.ts
var DEMO_GREETING = "Hi \u2014 what are you shopping for today?";
async function handleAgentChat(body, authHeader, rawEnv) {
  const env = readAgentEnv(rawEnv);
  const req = body;
  const agentId = typeof req?.agentId === "string" ? req.agentId.trim() : "";
  if (!agentId) {
    return {
      status: 400,
      body: { ok: false, error: "bad_request", message: "Missing agentId." }
    };
  }
  const messages = Array.isArray(req.messages) ? req.messages : [];
  const context = req.context ?? emptyContext();
  const conversationId = typeof req.conversationId === "string" ? req.conversationId : "anon";
  let catalog;
  let config;
  let branding;
  if (agentId === "demo") {
    catalog = new DemoCatalog();
    config = {
      storeName: "Urban Thread",
      branchName: "Orchard",
      tone: "Premium but approachable",
      currency: "USD",
      recommendationLimit: 4,
      rules: "Only recommend in-stock products. Free pickup, $5 delivery. Prefer the shopper\u2019s chosen location.",
      locationNames: catalog.locations.map((l) => l.name),
      multiLocation: true
    };
    branding = {
      storeName: config.storeName,
      branchName: config.branchName,
      agentName: "StyleSelf",
      greeting: DEMO_GREETING,
      currency: "USD",
      multiLocation: true,
      locations: config.locationNames,
      live: true,
      preview: false
    };
  } else {
    if (!env.supabaseUrl || !env.supabaseAnonKey) {
      return {
        status: 500,
        body: {
          ok: false,
          error: "not_configured",
          message: "The agent backend is not configured."
        }
      };
    }
    const supabase = createClient(env.supabaseUrl, env.supabaseAnonKey, {
      auth: { persistSession: false, autoRefreshToken: false },
      global: authHeader ? { headers: { Authorization: authHeader } } : {}
    });
    const storeRes = await supabase.from("stores").select("*").eq("slug", agentId).maybeSingle();
    if (storeRes.error) {
      console.error(`[agent ${conversationId}] store lookup failed`, storeRes.error);
      return {
        status: 500,
        body: {
          ok: false,
          error: "server",
          message: "Could not load this store right now. Try again shortly."
        }
      };
    }
    const store = storeRes.data;
    if (!store) {
      return {
        status: 404,
        body: {
          ok: false,
          error: "not_found",
          message: "No agent found at this address."
        }
      };
    }
    const [{ data: agentRow }, { data: locRows }] = await Promise.all([
      supabase.from("store_agents").select("*").eq("store_id", store.id).maybeSingle(),
      supabase.from("store_locations").select("id, name, is_primary").eq("store_id", store.id).order("is_primary", { ascending: false })
    ]);
    const locations = (locRows ?? []).map((l) => ({
      id: l.id,
      name: l.name
    }));
    const currency = agentRow?.currency ?? "USD";
    const preview = !store.agent_live;
    catalog = new DbCatalog(supabase, store.id, currency, locations);
    config = {
      storeName: store.name,
      branchName: store.branch_name,
      tone: agentRow?.tone ?? "Warm, concise, style-aware",
      currency,
      recommendationLimit: clampLimit(agentRow?.recommendation_limit),
      rules: agentRow?.rules ?? null,
      locationNames: locations.map((l) => l.name),
      multiLocation: locations.length > 1
    };
    branding = {
      storeName: store.name,
      branchName: store.branch_name,
      agentName: agentRow?.display_name ?? "StyleSelf",
      greeting: agentRow?.greeting ?? "What are you looking for today?",
      currency,
      multiLocation: locations.length > 1,
      locations: locations.map((l) => l.name),
      live: store.agent_live,
      preview
    };
  }
  if (messages.length === 0) {
    return {
      status: 200,
      body: {
        ok: true,
        agent: branding,
        message: branding.greeting,
        action: { type: "none" },
        context
      }
    };
  }
  if (!env.openaiApiKey) {
    return {
      status: 200,
      body: {
        ok: true,
        agent: branding,
        message: "This agent isn't fully set up yet \u2014 the shopping assistant is offline.",
        action: { type: "none" },
        context
      }
    };
  }
  try {
    const openai = new OpenAI({ apiKey: env.openaiApiKey });
    const out = await runTurn(openai, env.model, {
      messages,
      context,
      catalog,
      config
    });
    return { status: 200, body: { ok: true, agent: branding, ...out } };
  } catch (err) {
    console.error(`[agent ${conversationId}]`, err);
    return {
      status: 200,
      body: {
        ok: true,
        agent: branding,
        message: "Sorry \u2014 I hit a snag reaching the assistant. Try that again in a moment.",
        action: { type: "none" },
        context
      }
    };
  }
}
function clampLimit(v2) {
  const n = typeof v2 === "number" ? v2 : 5;
  return Math.min(8, Math.max(1, Math.round(n)));
}

// server/agent/vercel-entry.ts
var maxDuration = 60;
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ ok: false, error: "bad_request", message: "POST only." });
    return;
  }
  try {
    const auth = req.headers["authorization"];
    const authHeader = Array.isArray(auth) ? auth[0] : auth;
    const body = typeof req.body === "string" ? safeParse(req.body) : req.body ?? {};
    const result = await handleAgentChat(
      body,
      authHeader,
      process.env
    );
    res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[agent] invocation failed:", err);
    res.status(200).json({
      ok: false,
      error: "server",
      message: `The assistant hit an error: ${message}`
    });
  }
}
function safeParse(s) {
  try {
    return JSON.parse(s);
  } catch {
    return {};
  }
}
export {
  handler as default,
  maxDuration
};
