// GENERATED by 'npm run build:fn' from server/agent/ — do not edit.

// server/agent/checkout.ts
import { createClient } from "@supabase/supabase-js";

// server/agent/env.ts
var DEV_SIGNING_SECRET = "styleself-dev-unsafe-signing-secret";
function readAgentEnv(raw) {
  const pick = (...keys) => {
    for (const k of keys) {
      const v2 = raw[k];
      if (v2 && v2.trim()) return v2.trim();
    }
    return "";
  };
  return {
    openaiApiKey: pick("OPENAI_API_KEY"),
    model: pick("AI_MODEL") || "gpt-4o-mini",
    supabaseUrl: pick(
      "SUPABASE_URL",
      "VITE_SUPABASE_URL",
      "NEXT_PUBLIC_SUPABASE_URL"
    ),
    supabaseAnonKey: pick(
      "SUPABASE_ANON_KEY",
      "VITE_SUPABASE_ANON_KEY",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY"
    ),
    signingSecret: pick("AGENT_SIGNING_SECRET") || DEV_SIGNING_SECRET
  };
}

// server/agent/catalog.ts
function matchLocationId(locations, name) {
  if (name) {
    const n = name.trim().toLowerCase();
    const hit = locations.find((l) => l.name.toLowerCase() === n);
    if (hit) return hit.id;
    const partial = locations.find(
      (l) => l.name.toLowerCase().includes(n) || n.includes(l.name.toLowerCase())
    );
    if (partial) return partial.id;
  }
  return locations[0]?.id ?? null;
}
var DbCatalog = class {
  kind = "db";
  db;
  storeId;
  currency;
  locations;
  constructor(db, storeId, currency, locations) {
    this.db = db;
    this.storeId = storeId;
    this.currency = currency;
    this.locations = locations;
  }
  get multiLocation() {
    return this.locations.length > 1;
  }
  locationIdByName(name) {
    return matchLocationId(this.locations, name);
  }
  map(rows) {
    return rows.map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      brand: p.brand,
      style: p.style,
      gender: p.gender,
      material: p.material,
      care: p.care,
      category: p.category,
      priceCents: p.price_cents,
      currency: p.currency,
      imageUrl: p.image_url,
      variants: (p.product_variants ?? []).map((v2) => ({
        id: v2.id,
        size: v2.size,
        color: v2.color,
        colorHex: v2.color_hex ?? null,
        priceCents: v2.price_cents,
        stockByLocation: Object.fromEntries(
          (v2.inventory ?? []).map((i) => [i.location_id, i.quantity])
        )
      }))
    }));
  }
  async all() {
    const { data, error } = await this.db.from("products").select("*, product_variants(*, inventory(*))").eq("store_id", this.storeId).eq("status", "active");
    if (error) throw new Error(error.message);
    return this.map(data ?? []);
  }
  async byIds(ids) {
    if (ids.length === 0) return [];
    const { data, error } = await this.db.from("products").select("*, product_variants(*, inventory(*))").eq("store_id", this.storeId).in("id", ids);
    if (error) throw new Error(error.message);
    return this.map(data ?? []);
  }
};
var DemoCatalog = class {
  kind = "demo";
  currency = "USD";
  locations = [
    { id: "orchard", name: "Orchard" },
    { id: "vivocity", name: "VivoCity" },
    { id: "jurong", name: "Jurong East" }
  ];
  get multiLocation() {
    return true;
  }
  // module-level array — a "sale" within a warm instance is visible on reload
  products = DEMO_PRODUCTS;
  async all() {
    return this.products;
  }
  async byIds(ids) {
    return this.products.filter((p) => ids.includes(p.id));
  }
  locationIdByName(name) {
    return matchLocationId(this.locations, name);
  }
  decrementStock(variantId, locationId, qty) {
    for (const p of this.products) {
      const v2 = p.variants.find((x) => x.id === variantId);
      if (v2 && v2.stockByLocation[locationId] != null) {
        v2.stockByLocation[locationId] = Math.max(
          0,
          v2.stockByLocation[locationId] - qty
        );
        return;
      }
    }
  }
};
function v(id, size, color, stock, colorHex = null) {
  return { id, size, color, colorHex, priceCents: null, stockByLocation: stock };
}
var DEMO_PRODUCTS = [
  {
    id: "demo-linen-blazer",
    name: "Linen Blazer",
    description: "Relaxed-fit oatmeal linen blazer, half-lined with a natural shoulder. Reads smart without feeling stiff.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Mens",
    material: "100% linen",
    care: "Dry clean",
    category: "Blazers",
    priceCents: 8900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dlb-s-oat", "S", "Oatmeal", { orchard: 2, vivocity: 1, jurong: 0 }, "#E3D7BF"),
      v("dlb-m-oat", "M", "Oatmeal", { orchard: 4, vivocity: 2, jurong: 0 }, "#E3D7BF"),
      v("dlb-l-oat", "L", "Oatmeal", { orchard: 3, vivocity: 0, jurong: 1 }, "#E3D7BF")
    ]
  },
  {
    id: "demo-tailored-jacket",
    name: "Tailored Jacket",
    description: "Structured navy jacket with a sharp shoulder and a clean lapel. The formal end of the rail.",
    brand: "Urban Thread",
    style: "Formal",
    gender: "Mens",
    material: "Wool blend",
    care: "Dry clean",
    category: "Blazers",
    priceCents: 12900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dtj-m-nvy", "M", "Navy", { orchard: 2, vivocity: 1, jurong: 0 }, "#26314A"),
      v("dtj-l-nvy", "L", "Navy", { orchard: 1, vivocity: 1, jurong: 0 }, "#26314A")
    ]
  },
  {
    id: "demo-overshirt",
    name: "Relaxed Overshirt",
    description: "Lightweight taupe overshirt with chest pockets. Layer it open or button it up.",
    brand: "Urban Thread",
    style: "Casual",
    gender: "Unisex",
    material: "Cotton twill",
    care: "Machine wash cold",
    category: "Shirts",
    priceCents: 7200,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dos-s-tpe", "S", "Taupe", { orchard: 3, vivocity: 2, jurong: 4 }, "#B8A992"),
      v("dos-m-tpe", "M", "Taupe", { orchard: 6, vivocity: 3, jurong: 5 }, "#B8A992"),
      v("dos-l-tpe", "L", "Taupe", { orchard: 2, vivocity: 1, jurong: 3 }, "#B8A992")
    ]
  },
  {
    id: "demo-oxford",
    name: "Oxford Shirt",
    description: "Classic cotton oxford. Works under a blazer for dinner or on its own.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Unisex",
    material: "100% cotton",
    care: "Machine wash cold",
    category: "Shirts",
    priceCents: 4900,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dox-s-wht", "S", "White", { orchard: 8, vivocity: 6, jurong: 7 }, "#F4F1EA"),
      v("dox-m-wht", "M", "White", { orchard: 12, vivocity: 8, jurong: 10 }, "#F4F1EA"),
      v("dox-l-wht", "L", "White", { orchard: 5, vivocity: 4, jurong: 6 }, "#F4F1EA"),
      v("dox-m-blu", "M", "Sky Blue", { orchard: 4, vivocity: 3, jurong: 2 }, "#8FB3D9")
    ]
  },
  {
    id: "demo-trousers",
    name: "Wool Trousers",
    description: "Charcoal tapered wool trousers with a clean drape. Smart casual to formal.",
    brand: "Urban Thread",
    style: "Smart casual",
    gender: "Mens",
    material: "Wool blend",
    care: "Dry clean",
    category: "Trousers",
    priceCents: 9800,
    currency: "USD",
    imageUrl: null,
    variants: [
      v("dwt-30-chr", "30", "Charcoal", { orchard: 3, vivocity: 2, jurong: 1 }, "#3B3A37"),
      v("dwt-32-chr", "32", "Charcoal", { orchard: 5, vivocity: 4, jurong: 2 }, "#3B3A37"),
      v("dwt-34-chr", "34", "Charcoal", { orchard: 4, vivocity: 3, jurong: 2 }, "#3B3A37")
    ]
  }
];

// server/agent/signing.ts
import { createHmac, timingSafeEqual } from "node:crypto";
var b64url = (buf) => Buffer.from(buf).toString("base64url");
function sign(payload, secret) {
  const body = b64url(JSON.stringify(payload));
  const sig = createHmac("sha256", secret).update(body).digest("base64url");
  return `${body}.${sig}`;
}
function verify(token, secret) {
  if (typeof token !== "string" || !token.includes(".")) return null;
  const [body, sig] = token.split(".");
  if (!body || !sig) return null;
  const expected = createHmac("sha256", secret).update(body).digest("base64url");
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !timingSafeEqual(a, b)) return null;
  let payload;
  try {
    payload = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
  } catch {
    return null;
  }
  if (typeof payload.exp === "number" && Date.now() > payload.exp) return null;
  return payload;
}

// server/agent/tools.ts
function variantLabel(v2) {
  return [v2.size, v2.color].filter(Boolean).join(" / ") || "One size";
}

// server/agent/orders.ts
var FEE_CENTS = 500;
function simulateVisaAuth() {
  return { authorized: true };
}
function authCode() {
  return `VISA-${Math.random().toString(36).slice(2, 10).toUpperCase()}`;
}
async function lineRows(catalog, items) {
  const products = await catalog.byIds([...new Set(items.map((i) => i.productId))]);
  const byId = new Map(products.map((p) => [p.id, p]));
  return items.map((i) => {
    const p = byId.get(i.productId);
    const v2 = p?.variants.find((x) => x.id === i.variantId);
    const unit = v2?.priceCents ?? p?.priceCents ?? 0;
    return {
      name: p?.name ?? "Item",
      variantLabel: v2 ? variantLabel(v2) : null,
      quantity: i.quantity,
      lineTotalCents: unit * i.quantity
    };
  });
}
var demoOrders = /* @__PURE__ */ new Map();
async function simulateCheckout(catalog, input) {
  const key = `${input.conversationId}|${input.draftHash}`;
  const cached = demoOrders.get(key);
  if (cached) return cached;
  const visa = simulateVisaAuth();
  if (!visa.authorized) {
    return { ok: false, error: "declined", message: `Payment declined: ${visa.reason}` };
  }
  const locId = input.locationId ?? catalog.locations[0]?.id ?? null;
  const items = await lineRows(catalog, input.items);
  const subtotal = items.reduce((s, l) => s + l.lineTotalCents, 0);
  const fees = input.fulfillment === "delivery" ? FEE_CENTS : 0;
  if (locId && catalog.decrementStock) {
    for (const it of input.items) catalog.decrementStock(it.variantId, locId, it.quantity);
  }
  const confirmation = {
    ok: true,
    kind: "order",
    orderId: `demo_${Math.random().toString(36).slice(2, 10)}`,
    status: "paid",
    merchantName: input.merchantName,
    currency: input.currency,
    items,
    subtotalCents: subtotal,
    feesCents: fees,
    totalCents: subtotal + fees,
    visaAuthCode: authCode(),
    settlement: input.settlement,
    message: "Payment authorized and your order is confirmed."
  };
  demoOrders.set(key, confirmation);
  return confirmation;
}
async function runCheckout(supabase, storeId, catalog, input) {
  const visa = simulateVisaAuth();
  if (!visa.authorized) {
    return { ok: false, error: "declined", message: `Payment declined: ${visa.reason}` };
  }
  const { data, error } = await supabase.rpc("agent_checkout", {
    p_store: storeId,
    p_conversation: input.conversationId,
    p_draft_hash: input.draftHash,
    p_buyer_name: input.buyerName,
    p_buyer_email: input.buyerEmail,
    p_fulfillment: input.fulfillment,
    p_location: input.locationId,
    p_currency: input.currency,
    p_items: input.items.map((i) => ({ variant_id: i.variantId, quantity: i.quantity }))
  });
  if (error) {
    const m = error.message || "checkout failed";
    if (/insufficient stock/i.test(m)) {
      return {
        ok: false,
        error: "stock",
        message: "One of those items just sold out \u2014 ask the assistant for an alternative."
      };
    }
    if (/not available/i.test(m)) {
      return { ok: false, error: "not_found", message: "That item is no longer available." };
    }
    return { ok: false, error: "server", message: "The payment could not be completed." };
  }
  const order = data;
  const items = await lineRows(catalog, input.items);
  return {
    ok: true,
    kind: "order",
    orderId: order.id,
    status: "paid",
    merchantName: input.merchantName,
    currency: order.currency,
    items,
    subtotalCents: order.subtotal_cents,
    feesCents: order.fees_cents,
    totalCents: order.total_cents,
    visaAuthCode: order.visa_auth_code ?? authCode(),
    settlement: input.settlement,
    message: "Payment authorized and your order is confirmed."
  };
}

// server/agent/checkout.ts
var str = (v2) => typeof v2 === "string" && v2.trim() ? v2.trim() : void 0;
function fail(status, error, message) {
  return { status, body: { ok: false, error, message } };
}
async function handleCheckout(body, authHeader, rawEnv) {
  const env = readAgentEnv(rawEnv);
  const req = body ?? {};
  const action = str(req.action);
  const agentId = str(req.agentId);
  const conversationId = str(req.conversationId) || "anon";
  if (!agentId) return fail(400, "bad_request", "Missing agentId.");
  if (action !== "authorize" && action !== "pay") {
    return fail(400, "bad_request", "Unknown action.");
  }
  const draftToken = str(req.orderDraftToken);
  if (!draftToken) return fail(400, "bad_request", "Missing order token.");
  const draft = verify(draftToken, env.signingSecret);
  if (!draft || draft.kind !== "draft") {
    return fail(400, "expired", "This order has expired \u2014 ask the assistant to prepare it again.");
  }
  if (draft.agentId !== agentId || draft.conversationId !== conversationId) {
    return fail(400, "bad_request", "This order does not match your session.");
  }
  if (!Array.isArray(draft.items) || draft.items.length === 0) {
    return fail(400, "bad_request", "The order is empty.");
  }
  const resolved = await resolveAgent(agentId, authHeader, env);
  if (resolved === "unconfigured") {
    return fail(500, "server", "The agent backend is not configured.");
  }
  if (!resolved) return fail(404, "not_found", "No agent found at this address.");
  if (action === "authorize") {
    const buyerName = str(req.buyerName);
    const card = req.card ?? {};
    const last4 = str(card.last4);
    if (!buyerName || buyerName.length < 2) {
      return fail(400, "bad_request", "Enter the cardholder name.");
    }
    if (!last4 || !/^\d{4}$/.test(last4)) {
      return fail(400, "bad_request", "Enter valid card details.");
    }
    const shortage = await checkStock(resolved.catalog, draft);
    if (shortage) return fail(409, "stock", shortage);
    const now = Date.now();
    const token = sign(
      {
        kind: "auth",
        draftHash: draft.draftHash,
        agentId,
        conversationId,
        buyerName,
        iat: now,
        exp: now + 10 * 60 * 1e3
      },
      env.signingSecret
    );
    return {
      status: 200,
      body: {
        ok: true,
        kind: "authorization",
        token,
        verified: true,
        message: "Card authorized \u2014 payment is linked to this session."
      }
    };
  }
  const authToken = str(req.authorizationToken);
  if (!authToken) return fail(400, "bad_request", "Payment has not been authorized yet.");
  const auth = verify(authToken, env.signingSecret);
  if (!auth || auth.kind !== "auth" || auth.draftHash !== draft.draftHash || auth.agentId !== agentId || auth.conversationId !== conversationId) {
    return fail(400, "bad_request", "Authorization is invalid or expired \u2014 verify again.");
  }
  const input = {
    conversationId,
    draftHash: draft.draftHash,
    buyerName: auth.buyerName,
    buyerEmail: null,
    fulfillment: draft.fulfillment === "pickup" ? "pickup" : "delivery",
    locationId: draft.locationId ?? null,
    currency: draft.currency,
    items: draft.items,
    merchantName: resolved.merchantName,
    settlement: resolved.settlement
  };
  const result = resolved.kind === "demo" ? await simulateCheckout(resolved.catalog, input) : await runCheckout(resolved.supabase, resolved.storeId, resolved.catalog, input);
  if (!result.ok) {
    const status = result.error === "stock" ? 409 : result.error === "declined" ? 402 : 400;
    return { status, body: result };
  }
  return { status: 200, body: result };
}
async function resolveAgent(agentId, authHeader, env) {
  if (agentId === "demo") {
    return {
      kind: "demo",
      catalog: new DemoCatalog(),
      storeId: null,
      supabase: null,
      merchantName: "Urban Thread",
      settlement: "Urban Thread \xB7 DBS \u2022\u20224291"
    };
  }
  if (!env.supabaseUrl || !env.supabaseAnonKey) return "unconfigured";
  const supabase = createClient(env.supabaseUrl, env.supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
    global: authHeader ? { headers: { Authorization: authHeader } } : {}
  });
  const { data: store } = await supabase.from("stores").select("*").eq("slug", agentId).maybeSingle();
  if (!store) return null;
  const [{ data: agentRow }, { data: locRows }] = await Promise.all([
    supabase.from("store_agents").select("currency").eq("store_id", store.id).maybeSingle(),
    supabase.from("store_locations").select("id, name, is_primary").eq("store_id", store.id).order("is_primary", { ascending: false })
  ]);
  const locations = (locRows ?? []).map((l) => ({ id: l.id, name: l.name }));
  const currency = agentRow?.currency ?? "USD";
  const settlement = store.payout_account_last4 ? `${store.name} \xB7 ${store.payout_bank_name ?? "Bank"} \u2022\u2022${store.payout_account_last4}` : null;
  return {
    kind: "db",
    catalog: new DbCatalog(supabase, store.id, currency, locations),
    storeId: store.id,
    supabase,
    merchantName: store.name,
    settlement
  };
}
async function checkStock(catalog, draft) {
  const products = await catalog.byIds([...new Set(draft.items.map((i) => i.productId))]);
  const byId = new Map(products.map((p) => [p.id, p]));
  for (const it of draft.items) {
    const p = byId.get(it.productId);
    const v2 = p?.variants.find((x) => x.id === it.variantId);
    if (!p || !v2) return "One of those items is no longer available.";
    const stock = Object.values(v2.stockByLocation).reduce((a, b) => a + b, 0);
    if (stock < it.quantity) {
      return `${p.name} just sold out \u2014 ask the assistant for an alternative.`;
    }
  }
  return null;
}

// server/agent/checkout-entry.ts
var maxDuration = 30;
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ ok: false, error: "bad_request", message: "POST only." });
    return;
  }
  try {
    const auth = req.headers["authorization"];
    const authHeader = Array.isArray(auth) ? auth[0] : auth;
    const body = typeof req.body === "string" ? safeParse(req.body) : req.body ?? {};
    const result = await handleCheckout(
      body,
      authHeader,
      process.env
    );
    res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[agent-checkout] invocation failed:", err);
    res.status(200).json({
      ok: false,
      error: "server",
      message: `Checkout hit an error: ${message}`
    });
  }
}
function safeParse(s) {
  try {
    return JSON.parse(s);
  } catch {
    return {};
  }
}
export {
  handler as default,
  maxDuration
};
